name: .

on:
  workflow_dispatch:
  
jobs:
  In2Yt:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Pull Docker image
      run: docker pull qsdcbv/insta2yt:a1
    - name: Run Docker file
      run: |
           docker run qsdcbv/insta2yt:a1 sh -c "wget https://raw.githubusercontent.com/Rdxcj/Test3/main/57.py && ls -tgh && pwd && wget https://raw.githubusercontent.com/Rdxcj/Test3/main/z.py && firefox --version && which firefox && cp geckodriver /usr/local/bin && cp geckodriver /usr/bin && which geckodriver && geckodriver --version && python3 z.py"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: my-artifact # NOTE: same artifact name
          path: /shit
          compression-level: 9
