name: 1_

on:
  workflow_dispatch:

jobs:
  In2Yt:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull qsdcbv/insta2yt:a1

    - name: Run Docker container and copy screenshot
      run: |
           docker run --name in2yt -v "${{ github.workspace }}":/app qsdcbv/insta2yt:a1 sh -c "cp geckodriver /usr/local/bin && python3 -m venv 1; cd 1; ls -tgh"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: "yt"
          path: "yt.tar.gz"
          compression-level: 9
