name: Insta2YT Workflow

on:
  workflow_dispatch:

jobs:
  In2Yt:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Pull Docker image
      run: docker pull qsdcbv/insta2yt:a1
    - name: Run Docker file and Copy Artifact
      run: |
        docker run --rm -v "${GITHUB_WORKSPACE}/artifact_output:/container_output" qsdcbv/insta2yt:a1 sh -c "
          set -e
          wget https://raw.githubusercontent.com/Rdxcj/Test3/main/0.py -O /tmp/0.py
          cp geckodriver /usr/local/bin
          python3 /tmp/0.py # Your Python script that saves k.png to /usr/local/bin inside the container
          cp /usr/local/bin/k.png /container_output/k.png # Copy k.png from container to shared volume
        "
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: "y-artifact"
          path: "${GITHUB_WORKSPACE}/artifact_output/k.png" # Upload from the shared volume on the runner
          compression-level: 9
