name: .

on:
  workflow_dispatch:
  
jobs:
  In2Yt:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Pull Docker image
      run: docker pull qsdcbv/insta2yt:a1
    - name: Run Docker container and copy screenshot
      run: |
           docker run --name mycontainer qsdcbv/insta2yt:a1 sh -c "wget https://raw.githubusercontent.com/Rdxcj/Test3/main/0.py && cp geckodriver /usr/local/bin && python3 0.py"
           docker cp mycontainer:/usr/local/bin/k.png ./k.png
           docker rm mycontainer  # Clean up the container
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: "y-artifact"
          path: "k.png"
          compression-level: 9
