name: Run 57.py in Docker

on:
  workflow_dispatch:

jobs:
  In2Yt:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4  # Makes your repo files (like 57.py) available

    - name: Pull Docker image
      run: docker pull qsdcbv/insta2yt:a1

    - name: Run Docker container and copy screenshot
      run: |
           # Run container with repo files mounted to /app, then execute 57.py
           docker run \
             --name mycontainer \
             -v "${{ github.workspace }}":/app \  # Mount repo files to /app in container
             qsdcbv/insta2yt:a1 \
             sh -c "cp geckodriver /usr/local/bin && python3 /app/57.py"  # Use local 57.py

           # Copy screenshot from container to host
           docker cp mycontainer:/usr/local/bin/k.png ./k.png
           docker rm mycontainer  # Clean up

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: "y-artifact"
          path: "k.png"
          compression-level: 9
