name: Trash

on:
  workflow_dispatch:

jobs:
  In2Yt:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull qsdcbv/insta2yt:a1

    - name: Run Docker container and copy screenshot
      run: |
           docker run --name mycontainer -v "${{ github.workspace }}":/app qsdcbv/insta2yt:a1 sh -c "cp geckodriver /usr/local/bin && cat /app/home.tar.gz.parta* >/app/backup.tar.gz && tar -xvzf /app/backup.tar.gz -C /app > /dev/null 2>&1 && mkdir /app/yt_screenshot && python3 /app/1.py; cd app; ls -tgh; pwd"
           docker rm mycontainer
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: "y-artifact"
          path: "fucke.tar.gz"
          compression-level: 9
