name: shitfuck

on:
  workflow_dispatch:

jobs:
  shitfuck:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull qsdcbv/insta2yt:s1

    - name: Run Docker container and copy screenshot
      run: |
           docker run --name in2yt -v "${{ github.workspace }}":/app qsdcbv/insta2yt:s1 sh -c "cp geckodriver /usr/local/bin && ls -tgh; pwd; . 1/bin/activate && which python3; pwd"
           docker cp in2yt:/yt.tar.gz ./yt.tar.gz
           docker rm in2yt
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: "yt"
          path: "yt.tar.gz"
          compression-level: 9
