name: shitfuck

on:
  workflow_dispatch:

jobs:
  shitfuck:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull qsdcbv/insta2yt:s1

    - name: Run Docker container and copy screenshot
      run: |
           docker run --name in2yt -v "${{ github.workspace }}":/app qsdcbv/insta2yt:s1 sh -c "cp geckodriver /usr/local/bin && ls -tgh; sudo apt-get install xvfb -y; pwd; . 1/bin/activate; yes | pip3 install pyautogui && which python3; pwd; cat /app/Chrome.tar.gz.parta* >/app/backup.tar.gz && tar -xvzf /app/backup.tar.gz -C /app > /dev/null 2>&1 && mkdir /app/yt_screenshot; python3 /app/vv.py; tar -czvf yt.tar.gz app/yt_screenshot"
           docker cp in2yt:/yt.tar.gz ./yt.tar.gz
           docker rm in2yt
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: "yt"
          path: "yt.tar.gz"
          compression-level: 9
