name: Insta2YT Workf

on:
  workflow_dispatch:

jobs:
  In2Yt:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Pull Docker image
      run: docker pull qsdcbv/insta2yt:a1
    - name: Run Docker container and copy script/screenshot
      run: |
        docker run --name mycontainer -d qsdcbv/insta2yt:a1 sleep infinity # Run container in detached mode

        # Copy your 57.py script into the running container
        docker cp 57.py mycontainer:/app/

        # Execute the script inside the container
        docker exec mycontainer sh -c "
          cp geckodriver /usr/local/bin
          python3 /app/57.py # Run the script from /app
          cp /usr/local/bin/k.png /app/k.png # Ensure screenshot is in /app
        "

        # Copy the screenshot back to the runner
        docker cp mycontainer:/app/k.png ./k.png

        docker stop mycontainer
        docker rm mycontainer
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "y-artifact"
        path: "k.png"
        compression-level: 9
