name: in2yt

on:
  workflow_dispatch:

jobs:
  In2Yt:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull qsdcbv/insta2yt:a1

    - name: Run Docker container and copy screenshot
      run: |
           docker run --name in2yt -v "${{ github.workspace }}":/app qsdcbv/insta2yt:a1 sh -c "cp geckodriver /usr/local/bin && cat /app/home.tar.gz.parta* >/app/backup.tar.gz && tar -xvzf /app/backup.tar.gz -C /app > /dev/null 2>&1 && mkdir /app/yt_screenshot && python3 /app/in2yt.py; tar -czvf yt.tar.gz app/yt_screenshot"
           docker cp in2yt:/yt.tar.gz ./yt.tar.gz
           docker rm in2yt
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: "yt"
          path: "yt.tar.gz"
          compression-level: 9
